# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Learning Jekyll
email: laugustofrontend@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Development website para learn jekyll and liquid frontmatter
baseurl: "/learning_jekyll" # the subpath of your site, e.g. /blog
url: "http://lucasaugusto.eti.br" # the base hostname & protocol for your site
twitter_username: laugustofront
github_username:  lucasaugustofrontend

# Build settings
markdown: kramdown

permalink: /:categories/:title
